spring:
  application:
    name: wx-einvite
server:
  port: 8444
qiniu:
  accessKey: jDnQXipsdRsg4_zUmWQxTtWg84odBuHwYWKOda4W
  secretKey: JCJMi6dCtlhySIeLRoHDnvFxlLiiOB_rbvn1_6d1
  bucketName: e-invite
  domain: http://oj9704ax3.bkt.clouddn.com/