spring:
  application:
    name: wx-einvite
server:
  port: 443
  ssl:
    key-password:
    key-store: "classpath:www.e-invite.cn.pfx"
    key-store-type: PKCS12
qiniu:
  accessKey: jDnQXipsdRsg4_zUmWQxTtWg84odBuHwYWKOda4W
  secretKey: JCJMi6dCtlhySIeLRoHDnvFxlLiiOB_rbvn1_6d1
  bucketName: e-invite
  domain: http://oj9704ax3.bkt.clouddn.com/